formulas = [
    "ladder_score ~ 1",
    "ladder_score ~ freedom_to_make_life_choices",
    "ladder_score ~ healthy_life_expectancy",
    "ladder_score ~ regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator",
    "ladder_score ~ healthy_life_expectancy + regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices:healthy_life_expectancy",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + freedom_to_make_life_choices:healthy_life_expectancy",
    "ladder_score ~ freedom_to_make_life_choices:regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + freedom_to_make_life_choices:regional_indicator",
    "ladder_score ~ healthy_life_expectancy:regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + healthy_life_expectancy:regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices:healthy_life_expectancy + freedom_to_make_life_choices:regional_indicator + healthy_life_expectancy:regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + freedom_to_make_life_choices:healthy_life_expectancy + freedom_to_make_life_choices:regional_indicator + healthy_life_expectancy:regional_indicator",
    "ladder_score ~ freedom_to_make_life_choices + freedom_to_make_life_choices:healthy_life_expectancy",
    "ladder_score ~ healthy_life_expectancy + freedom_to_make_life_choices:healthy_life_expectancy",
    "ladder_score ~ freedom_to_make_life_choices + freedom_to_make_life_choices:regional_indicator",
    "ladder_score ~ regional_indicator + freedom_to_make_life_choices:regional_indicator",
    "ladder_score ~ healthy_life_expectancy + healthy_life_expectancy:regional_indicator",
    "ladder_score ~ regional_indicator + healthy_life_expectancy:regional_indicator",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (healthy_life_expectancy + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (0 + freedom_to_make_life_choices + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ regional_indicator + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (healthy_life_expectancy | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + (0 + freedom_to_make_life_choices + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ 1 + (0 + freedom_to_make_life_choices | healthy_life_expectancy)",
    "ladder_score ~ 1 + (0 + freedom_to_make_life_choices | regional_indicator)",
    "ladder_score ~ healthy_life_expectancy + (0 + healthy_life_expectancy | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ 1 + (0 + healthy_life_expectancy | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (0 + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ healthy_life_expectancy + (0 + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (1 | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (0 + healthy_life_expectancy | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (0 + freedom_to_make_life_choices + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (1 | regional_indicator)",
    "ladder_score ~ 1 + (1 | healthy_life_expectancy)",
    "ladder_score ~ 1 + (regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (0 + freedom_to_make_life_choices + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ regional_indicator + (0 + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (1 | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (0 + freedom_to_make_life_choices | healthy_life_expectancy)",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (1 | healthy_life_expectancy)",
    "ladder_score ~ regional_indicator + (0 + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (0 + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ healthy_life_expectancy + (1 | regional_indicator)",
    "ladder_score ~ healthy_life_expectancy + (1 | healthy_life_expectancy)",
    "ladder_score ~ healthy_life_expectancy + (healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (1 | regional_indicator)",
    "ladder_score ~ 1 + (0 + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ 1 + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (1 | regional_indicator)",
    "ladder_score ~ 1 + (0 + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + (0 + freedom_to_make_life_choices | healthy_life_expectancy)",
    "ladder_score ~ 1 + (freedom_to_make_life_choices | regional_indicator)",
    "ladder_score ~ regional_indicator + (1 | healthy_life_expectancy)",
    "ladder_score ~ 1 + (freedom_to_make_life_choices + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ 1 + (healthy_life_expectancy + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + (1 | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + (1 | healthy_life_expectancy)",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (0 + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + (0 + freedom_to_make_life_choices | regional_indicator)",
    "ladder_score ~ 1 + (0 + healthy_life_expectancy + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (freedom_to_make_life_choices + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (0 + freedom_to_make_life_choices + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ regional_indicator + (1 | regional_indicator)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + (1 | regional_indicator)",
    "ladder_score ~ healthy_life_expectancy + regional_indicator + (0 + healthy_life_expectancy + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + (0 + healthy_life_expectancy + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (1 | regional_indicator)",
    "ladder_score ~ healthy_life_expectancy + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ 1 + (freedom_to_make_life_choices | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (0 + freedom_to_make_life_choices | regional_indicator)",
    "ladder_score ~ 1 + (freedom_to_make_life_choices + regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ 1 + (healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ healthy_life_expectancy + (healthy_life_expectancy | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + (freedom_to_make_life_choices + healthy_life_expectancy | regional_indicator)",
    "ladder_score ~ regional_indicator + (regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + (1 | freedom_to_make_life_choices)",
    "ladder_score ~ freedom_to_make_life_choices + (freedom_to_make_life_choices | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + (1 | regional_indicator)",
    "ladder_score ~ freedom_to_make_life_choices + regional_indicator + (0 + regional_indicator | freedom_to_make_life_choices)",
    "ladder_score ~ regional_indicator + (regional_indicator | healthy_life_expectancy)",
    "ladder_score ~ freedom_to_make_life_choices + (freedom_to_make_life_choices | regional_indicator)",
    "ladder_score ~ freedom_to_make_life_choices + healthy_life_expectancy + regional_indicator + (0 + freedom_to_make_life_choices + healthy_life_expectancy | regional_indicator)"
]
